behaviors:
  Tom:
    trainer_type: ppo
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: true
    hyperparameters:
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      batch_size: 4096
      buffer_size: 20480
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 256
    max_steps: 15000000 #10000000 takes abt 5hrs
    summary_freq: 5000

  Jerry:
    trainer_type: ppo
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: true
    hyperparameters:
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      batch_size: 4096
      buffer_size: 20480
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 256
    max_steps: 15000000
    summary_freq: 5000
